### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by Jbonez87** [codemzy/mern-auth#1]
Please provide start up documentation and proper configuration instructions to load this. Created a private folder and a .env file that pointed to a port and it would not register the port's existence.

**Comment by codemzy** [comment]
Hey, the private directory needs to be outside the project directory... so structure should be something like...

- private
- mern-auth
-- app
-- public
-- server

So completely outside the the project directory (up another level from the server folder). Then put your .env file inside the private folder, and the server.js config should pick it up. You also need to defined the database `process.env.MONGO_URL` in the .env file.

**Comment by codemzy** [comment]
Added get started instructions to README in commit 1aeac267c1627db3a2caa719e6acccb857ffae54

**Comment by Jbonez87** [comment]
Thank you! Your code is awesome btw
