### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by Jbonez87** [codemzy/mern-auth#2]
I was able to register and I received a registration email, but the app itself would redirect to http://localhost/app instead of localhost:(port)/app. The error I am getting says my connection was refused on login.

**Comment by codemzy** [comment]
Hi,

Thanks for letting me know. I didn't use a port in the url when I was developing so hadn't picked this up.

I have made some updates this morning (changing some React redirects on login and logout), to fix this issue. 

Commit 6c575c26971269685f99d62b1f5fa1ec64969c32
and 
Commit 805431f4bb982ac161a49d2ebd898fb8e6419782

If you pull down the latest version this should be fixed :)
